# Generated by Django 5.1.15 on 2026-03-31 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('grateful', 'Grateful')], default='', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='tags.tag')),
            ],
            options={
                'db_table': 'entries_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
